% ########################
% ### 1D deforestation ###
% ########################

% Last version: Aug 7 2025

% ######################################################
% ### Deforestation Model with Agribusiness Dynamics ###
% ######################################################

clear all; clc; close all;

addpath ..\functions\

% ##################
% ### Parameters ###
% ##################

i = 5; % 0 = pi is zero and A decreasing
       % 1 = Agribusiness in the vertex
       % 2 = Sigma as an obstacle for agribusiness
       % 3 = Agribusiness in the middle
       % 4 = More Agribusinesses
       % 5 = Random A once again

% #######################################
% ### pi =0 and A decreasing (static) ###
% #######################################


if i == 0 

    params = struct('N',15,...
                    'beta',0.10,...
                    'alpha',0.75,...
                    'pi',0, ...
                    'Tlag',2,...
                    'Tmax',10,...
                    'delta',1,...
                    'tau',1.2,...
                    'wage',1, ...
                    'elasticity',1.5,...
                    'Sbar',6,...
                    'pI',1,...
                    'rho',1.5);
    
    A = linspace(3.1,1.1, params.N);                % Productivity > 1
    F = 1.8*ones(1,params.N);               % Homogeneous deforestation cost
    L = zeros(1,params.N);  % Legal status (1 = protected, 0 = unprotected)
                                     % everything is protected (static case)
    w = params.wage * ones(1,params.N);            % Constant wage
    
    D = zeros(1, params.N, params.Tmax); D(1,1,1) = 1; % Agrinusiness starts in one of the vertices
    O = zeros(1, params.N, params.Tmax); O_aux = rand(1,params.N); O(:,:,1) = D(1,1,1).*O_aux;
    Agribusiness = zeros(1, params.N, params.Tmax); Agribusiness(1,1,1) = 1; % Agribusiness starts in one of the vertices
    
    SolveDeforestation1D(params, A, F, O, D, L, Agribusiness, O_aux, 1,true)
end
% ##################################
% ### Agribusiness in the vertex ###
% ##################################

if i == 1

   params = struct('N',15,...
                   'beta',0.10,...
                   'alpha',0.75,...
                   'pi',.5, ...
                   'Tlag',2,...
                   'Tmax',20,...
                   'delta',1,...
                   'tau',1.2,...
                   'wage',1, ...
                   'elasticity',1.5,...
                   'Sbar',7,...
                   'pI',1,...
                   'rho',1.5);
  
    A = 2.*ones(1,params.N);                % Productivity > 1
    F = 1.8.*ones(1,params.N);               % Homogeneous deforestation cost
    L = zeros(1,params.N); L(1,1:(params.N+1)/2) = 1;  % Legal status (1 = protected, 0 = unprotected)
                                     % everything is protected (static case)
    w = params.wage * ones(1,params.N);            % Constant wage
    
    D = zeros(1, params.N, params.Tmax); D(1,end,1) = 1; % Agrinusiness starts in one of the vertices
    O = zeros(1, params.N, params.Tmax); O_aux = rand(1,params.N); O(:,:,1) = D(1,1,1).*O_aux;
    R = zeros(1, params.N, params.Tmax); 
    Agribusiness = zeros(1, params.N, params.Tmax); Agribusiness(1,end,1) = 1; % Agrinusiness starts in one of the vertices
    
    SolveDeforestation1D(params, A, F, O, D, L, Agribusiness, O_aux, 1,false)
end

if i == 2
   params = struct('N',16,...
                   'beta',0.10,...
                   'alpha',0.75,...
                   'pi',.5, ...
                   'Tlag',2,...
                   'Tmax',20,...
                   'delta',1,...
                   'tau',1.2,...
                   'wage',1, ...
                   'elasticity',1.5,...
                   'Sbar',5.5,...
                   'pI',1,...
                   'rho',1.5);
    
    A = 2.*ones(1,params.N);                % Productivity > 1
    F = 1.8*ones(1,params.N);               % Homogeneous deforestation cost
    L = zeros(1,params.N); L(1,1:params.N/2) = 1;  % Legal status (1 = protected, 0 = unprotected)
                                     % everything is protected (static case)
    w = params.wage * ones(1,params.N);            % Constant wage
    
    D = zeros(1, params.N, params.Tmax); D(1,end,1) = 1; % Agrinusiness starts in one of the vertices
    O = zeros(1, params.N, params.Tmax); O_aux = rand(1,params.N); O(:,:,1) = D(1,1,1).*O_aux;
    R = zeros(1, params.N, params.Tmax); 
    Agribusiness = zeros(1, params.N, params.Tmax); Agribusiness(1,end,1) = 1; % Agrinusiness starts in one of the vertices
    
    SolveDeforestation1D(params, A, F, O, D, L, Agribusiness, O_aux, 1,true)
end

% ##################################
% ### Agribusiness in the middle ###
% ##################################

if i == 3

 params = struct('N',16,...
                 'beta',0.10,...
                 'alpha',0.675,...
                 'pi',.8, ...
                 'Tlag',2,...
                 'Tmax',20,...
                 'delta',1,...
                 'tau',1.2,...
                 'wage',1, ...
                 'elasticity',1.5,...
                 'Sbar',6,...
                 'pI',1,...
                 'rho',1.5);    
    
    A = 2.1.*ones(1,params.N);                       % Productivity > 1
    F = 1.65*ones(1,params.N);                      % Homogeneous deforestation cost
    L = zeros(1,params.N); L(1,2) = 1; L(1,13) = 1;  % Legal status (1 = protected, 0 = unprotected)
    w = params.wage * ones(1,params.N);                   % Constant wage
    
    D = zeros(1, params.N, params.Tmax); D(1,8,1) = 1; % Agrinusiness starts in one of the middle
    O = zeros(1, params.N, params.Tmax); O_aux = rand(1,params.N); O(:,:,1) = D(1,1,1).*O_aux;
    R = zeros(1, params.N, params.Tmax); 
    Agribusiness = zeros(1, params.N, params.Tmax); Agribusiness(1,8,1) = 1; % Agrinusiness starts in one of the vertices
    
    SolveDeforestation1D(params, A, F, O, D, L, Agribusiness, O_aux, 1,true)
end

% ##################################
% ### Agribusiness in the middle ###
% ##################################

if i == 4

 params = struct('N',100,...
                 'beta',0.10,...
                 'alpha',0.7,...
                 'pi',.55, ...
                 'Tlag',2,...
                 'Tmax',20,...
                 'delta',1,...
                 'tau',1.2,...
                 'wage',1, ...
                 'elasticity',1.5,...
                 'Sbar',10,...
                 'pI',1,...
                 'rho',1.5);  
    
    A = 2.1.*ones(1,params.N);                      % Productivity > 1
    F = 1.65*ones(1,params.N);                      % Homogeneous deforestation cost
    L = zeros(1,params.N); L(1,19) = 1; L(1,21) = 1;  % Legal status (1 = protected, 0 = unprotected)
    w = params.wage * ones(1,params.N);                   % Constant wage
    
    D = zeros(1, params.N, params.Tmax); D(1,20,1) = 1; D(1,40,1) = 1;
                           D(1,60,1) = 1; D(1,80,1) = 1;% Agrinusiness starts in one of the middle
    O = zeros(1, params.N, params.Tmax); O_aux = rand(1,params.N); O(:,:,1) = D(1,1,1).*O_aux;
    R = zeros(1, params.N, params.Tmax); 
    Agribusiness = zeros(1, params.N, params.Tmax); Agribusiness(1,20,1) = 1; Agribusiness(1,40,1) = 1; % Agrinusiness starts in one of the vertices
                                      Agribusiness(1,60,1) = 1; Agribusiness(1,80,1) = 1;
    SolveDeforestation1D(params, A, F, O, D, L, Agribusiness, O_aux, 1,false)
end

if i == 5

 params = struct('N',100,...
                 'beta',0.10,...
                 'alpha',0.75,...
                 'pi',.5, ...
                 'Tlag',2,...
                 'Tmax',20,...
                 'delta',1,...
                 'tau',1.2,...
                 'wage',1, ...
                 'elasticity',1.5,...
                 'Sbar',7,...
                 'pI',1,...
                 'rho',1.5);  
    
    A = (1.4+rand(1,params.N)).*ones(1,params.N);                % Productivity > 1
    F = 1.8.*ones(1,params.N);               % Homogeneous deforestation cost
    L = zeros(1,params.N); L(1,1:(params.N/2)) = 1;  % Legal status (1 = protected, 0 = unprotected)
                                     % everything is protected (static case)
    w = params.wage * ones(1,params.N);            % Constant wage
    
    D = zeros(1, params.N, params.Tmax); D(1,end,1) = 1; % Agrinusiness starts in one of the vertices
    O = zeros(1, params.N, params.Tmax); O_aux = rand(1,params.N); O(:,:,1) = D(1,1,1).*O_aux;
    R = zeros(1, params.N, params.Tmax); 
    Agribusiness = zeros(1, params.N, params.Tmax); Agribusiness(1,end,1) = 1; % Agrinusiness starts in one of the vertices
    
    SolveDeforestation1D(params, A, F, O, D, L, Agribusiness, O_aux, 1,true)
end
